### ISSUE TITLE
Repeat overlay

### ISSUE THREAD

**Issue by litsou** [AvarianKnight/3dme#2]
If I type two sentences quickly, they will overlap
![image](https://user-images.githubusercontent.com/59511848/123516481-ce703800-d6ce-11eb-83fd-4c67d1420b2e.png)

**Comment by hAKIZOR** [comment]
@AvarianKnight any update :( ?

**Comment by hAKIZOR** [comment]
@AvarianKnight i have an idea... we can set a counter (clientside) where every time we write "/me..." the counter increase... and this counter will be the "height" of the position on the head.. Of course when the text disappear the counter decrease.

**Comment by AvarianKnight** [comment]
Fixed in latest release
