### ISSUE TITLE
Lua Question

### ISSUE THREAD

**Issue by Sojobo** [AvarianKnight/3dme#5]
Hey dude, this isn't really an issue, more of a question - I noticed that in the client.lua:31, you're using a plus equals.. My linter is showing it as an error and as far as I knew, plus equals isn't supported in lua.. and yet it runs and works so.. what? haha

**Comment by AvarianKnight** [comment]
Fivem uses CfxLua, so you can use most modern math symbols. If you use VS Code I suggest using sumneko's Lua Langauge Server, as it lets you add them as "Nonstandard Symbols" under the extension settings. It also allows you to use backticks (runtime Jenkins) without any issues.

**Comment by AvarianKnight** [comment]
You can see more stuff you can do [here](https://github.com/gottfriedleibniz/lua)
